[package]
name = "pencil_api"
version = "0.1.0"
edition = "2024"

[dependencies]
snowflaked = "1.0.3"
bcrypt = "0.17.0"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.219"
rand = "0.9.2"
serde_json = "1.0.142"
tokio = "1.47.1"
